// constants/sceneIDs.js

export const SCENE = {
  // 00. 연락 여부
  CONTACT_DECISION: "CONTACT_DECISION",

  // 01. 첫 메시지
  CONTACT_START: "CONTACT_START",

  // 02. 약속 조율
  CONTACT_SCHEDULING: "CONTACT_SCHEDULING",
  CONTACT_SCHEDULING_WAIT: "CONTACT_SCHEDULING_WAIT",

  // 03. 저녁 식사 도착
  DINNER_MEET: "DINNER_MEET",

  // 04. 저녁 대화 & 분기
  DINNER_TALK: "DINNER_TALK",
  DINNER_FLOW: "DINNER_FLOW",
  DINNER_INFP_MOMENT: "DINNER_INFP_MOMENT",

  // 05. 카페 이동
  CAFE_MOVE: "CAFE_MOVE",

  // 06. 카페 대화
  CAFE_TALK: "CAFE_TALK",
  CAFE_FLOW: "CAFE_FLOW",
  CAFE_INFP_MOMENT: "CAFE_INFP_MOMENT",

  // 07. 산책 제안
  WALK_SUGGEST: "WALK_SUGGEST",

  // 08. 산책 대화
  WALK_TALK: "WALK_TALK",

  // 09. 엔딩
  ENDING_ONE: "ENDING_ONE",
};
