// constants/sceneIDs.js

export const SCENE = {
  // 00. 프로필 소개 (프롤로그)
  PROLOGUE: "PROLOGUE",
  CONTACT_DECISION: "CONTACT_DECISION",
  CONTACT_START_SELF: "CONTACT_START_SELF",
  CONTACT_START_NPC: "CONTACT_START_NPC",
  CONTACT_START_COMMON: "CONTACT_START_COMMON",
  CONTACT_SCHEDULING: "CONTACT_SCHEDULING",
  CONTACT_SCHEDULING_WAIT: "CONTACT_SCHEDULING_WAIT",
  DINNER_MEET: "DINNER_MEET",
  DINNER_TALK: "DINNER_TALK",
  DINNER_FLOW: "DINNER_FLOW",
  DINNER_INFP_MOMENT: "DINNER_INFP_MOMENT",
  CAFE_MOVE: "CAFE_MOVE",
  CAFE_TALK: "CAFE_TALK",
  WALK_SUGGEST: "WALK_SUGGEST",
  ENDING_ONE: "ENDING_ONE",
};
